### ISSUE TITLE
opposite directions in objectives

### ISSUE THREAD

**Issue by nikorose87** [ppgaluzio/MOBOpt#5]
Hi again,

Sorry for writing so soon, I am setting a bi-optimal optimization problem, in which f1 needs to be minimized, while the f2 needs to be maximized. What I did was to change the sign in the maximized output. However, while the optimization was running, the f1 is being optimized but the f2 also did that. 

Am I interpreting the settings in a proper manner? I do not why both were minimized.

Thanks

**Comment by ppgaluzio** [comment]
The algorithm was implemented as to maximize the objectives, so in this case, you need to change the signs when implementing your objective function:

```python
def objective(x):
    ....
    return [-f1, f2]   # f1 is going to be minimized and f2 will be maximized
```

**Comment by nikorose87** [comment]
It is running, however I had the feature `mar_or_min='min'`. That is why I inverted the max function.
